// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package system

func (System) DescFishShell() string {
	return "Installs fish and sets it as paul's login shell (earth, zen, rocky)"
}

func (System) DescHosts() string { return "Manages the fleet block of /etc/hosts (earth)" }

func (System) DescUptimed() string { return "Installs and enables the uptimed daemon (earth, zen)" }

func (System) DescWireguard() string {
	return "Keeps /etc/wireguard and the wg0/wg1 configs private (earth, perms only)"
}
