// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package system

func (System) DescHosts() string { return "Manages the fleet block of /etc/hosts (earth)" }

func (System) DescWireguard() string {
	return "Keeps /etc/wireguard and the wg0/wg1 configs private (earth, perms only)"
}
