// Code generated by gonf-desc from the task methods' doc comments. DO NOT EDIT.

package home

func (HomeTasks) DescAgents() string { return "Installs agent command/skill symlinks" }

func (HomeTasks) DescBash() string { return "Installs bash configuration symlinks" }

func (HomeTasks) DescCalendar() string { return "Installs ~/.calendar from private repo" }

func (HomeTasks) DescFish() string { return "Installs fish conf.d symlink" }

func (HomeTasks) DescFishCompletions() string { return "Installs fish completions" }

func (HomeTasks) DescGhostty() string { return "Installs ~/.config/ghostty" }

func (HomeTasks) DescGitconfig() string { return "Sets global git config (not on macOS)" }

func (HomeTasks) DescGitsyncer() string { return "Installs gitsyncer config symlink" }

func (HomeTasks) DescHelix() string { return "Installs ~/.config/helix" }

func (HomeTasks) DescHexai() string { return "Installs ~/.config/hexai (Linux)" }

func (HomeTasks) DescLazygit() string { return "Installs ~/.config/lazygit" }

func (HomeTasks) DescOpencode() string { return "Installs ~/.config/opencode" }

func (HomeTasks) DescPipewire() string { return "Installs pipewire high-res config (Linux)" }

func (HomeTasks) DescQuickedit() string { return "Manages ~/QuickEdit symlinks" }

func (HomeTasks) DescScripts() string { return "Installs ~/scripts" }

func (HomeTasks) DescSignature() string { return "Installs ~/.signature" }

func (HomeTasks) DescSsh() string { return "Installs ~/.ssh/config" }

func (HomeTasks) DescSway() string { return "Installs sway and waybar config (Linux)" }

func (HomeTasks) DescSystemdUser() string { return "Installs and enables systemd user units" }

func (HomeTasks) DescTaskwarrior() string { return "Installs ~/.taskrc (Taskwarrior 3.x)" }

func (HomeTasks) DescTimesamurai() string { return "Installs ~/.config/timesamurai" }

func (HomeTasks) DescTmux() string { return "Installs ~/.config/tmux" }

func (HomeTasks) DescVale() string { return "Installs ~/.vale.ini symlink" }
